# Generated by Django 5.2.12 on 2026-04-30 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="address",
            field=models.TextField(max_length=255),
        ),
    ]
