# Generated by Django 5.2.12 on 2026-05-04 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0002_alter_customer_address"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customer",
            old_name="deleted_status",
            new_name="order_status",
        ),
    ]
