# Generated by Django 5.2.12 on 2026-05-04 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0003_rename_deleted_status_customer_order_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customer",
            old_name="order_status",
            new_name="deleted_status",
        ),
    ]
