# Generated by Django 5.2.12 on 2026-04-30 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_alter_ordereditem_owner_alter_ordereditem_product"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ordereditem",
            old_name="owner",
            new_name="order",
        ),
    ]
