# Generated by Django 5.2.12 on 2026-04-16 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("caption", models.CharField(default="JINSCART", max_length=255)),
                (
                    "banner_image_url",
                    models.ImageField(
                        blank=True, null=True, upload_to="media/site_settings/"
                    ),
                ),
            ],
        ),
    ]
